import h5py
import numpy as np
import matplotlib.pyplot as plt
import os
import struct

print("=== Constellation BL4S - HDF5 Calorimeter Data Analysis ===")

# The script expects the path to the H5 file generated by Constellation
h5_file_path = input("Lütfen HDF5 dosyasının yolunu girin (ör. /Users/kayrayavuz/Desktop/DATA/run_9.h5): ").strip()
if not os.path.exists(h5_file_path):
    print(f"Hata: {h5_file_path} bulunamadı!")
    exit(1)

output_dir = os.path.dirname(h5_file_path)

# Verileri tutacağımız yapılar (Her kanal için liste)
channels = 16
times = {ch: [] for ch in range(channels)}
num_hits = {ch: [] for ch in range(channels)}
amplitudes = {ch: [] for ch in range(channels)}

print(f"\n--- Reading HDF5 File: {h5_file_path} ---")

with h5py.File(h5_file_path, "r") as f:
    # H5DataWriter saves data under /data or similar depending on the tags
    # Let's iterate through all groups to find calorimeter data
    total_events = 0
    
    def process_node(name, node):
        global total_events
        if isinstance(node, h5py.Dataset):
            # Check if this dataset belongs to Calorimeter
            # Constellation H5DataWriter groups by name/type depending on tags
            if ("calorimeter" in name.lower() or "mockcalorimeter" in name.lower()) and "block" in name.lower():
                data = node[:]
                raw_bytes = data.tobytes()
                # Her kanal 8 byte: <H B x f (Amplitude, num_hits, pad, time)
                if len(raw_bytes) == channels * 8:
                    total_events += 1
                    for ch in range(channels):
                        offset = ch * 8
                        channel_data = raw_bytes[offset:offset+8]
                        amp, n_hits, time_val = struct.unpack('<H B x f', channel_data)
                        
                        amplitudes[ch].append(amp)
                        num_hits[ch].append(n_hits)
                        times[ch].append(time_val)

    f.visititems(process_node)

print(f"Processed {total_events} calorimeter events.")

if total_events == 0:
    print("No calorimeter data found in the file or format mismatch.")
    exit(1)

print("\n--- Generating Plots ---")

# 1. Amplitude (QDC) Plot
fig_amp, axes_amp = plt.subplots(4, 4, figsize=(16, 12))
axes_amp = axes_amp.flatten()
for ch in range(channels):
    ax = axes_amp[ch]
    ax.hist(amplitudes[ch], bins=50, range=(0, 5000), color="#1f77b4", histtype="stepfilled", alpha=0.7)
    ax.set_title(f"Calorimeter Ch{ch:02d} Amplitude", fontsize=10, fontweight="bold")
    ax.set_xlabel("QDC Counts", fontsize=8)
    ax.set_ylabel("Events", fontsize=8)
    ax.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
amp_plot_path = os.path.join(output_dir, "calorimeter_amplitude.png")
plt.savefig(amp_plot_path, dpi=200)
plt.close()
print(f"Saved Amplitude Plot to: {amp_plot_path}")

# 2. Number of Hits Plot
fig_hits, axes_hits = plt.subplots(4, 4, figsize=(16, 12))
axes_hits = axes_hits.flatten()
for ch in range(channels):
    ax = axes_hits[ch]
    ax.hist(num_hits[ch], bins=6, range=(-0.5, 5.5), color="#ff7f0e", histtype="stepfilled", alpha=0.7)
    ax.set_title(f"Calorimeter Ch{ch:02d} Num Hits", fontsize=10, fontweight="bold")
    ax.set_xlabel("# Hits", fontsize=8)
    ax.set_ylabel("Events", fontsize=8)
    ax.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
hits_plot_path = os.path.join(output_dir, "calorimeter_num_hits.png")
plt.savefig(hits_plot_path, dpi=200)
plt.close()
print(f"Saved Number of Hits Plot to: {hits_plot_path}")

# 3. Time (TDC) Plot
fig_time, axes_time = plt.subplots(4, 4, figsize=(16, 12))
axes_time = axes_time.flatten()
for ch in range(channels):
    ax = axes_time[ch]
    ax.hist(times[ch], bins=50, range=(0, 1000), color="#2ca02c", histtype="stepfilled", alpha=0.7)
    ax.set_title(f"Calorimeter Ch{ch:02d} Time", fontsize=10, fontweight="bold")
    ax.set_xlabel("Time [ns]", fontsize=8)
    ax.set_ylabel("Events", fontsize=8)
    ax.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
time_plot_path = os.path.join(output_dir, "calorimeter_time.png")
plt.savefig(time_plot_path, dpi=200)
plt.close()
print(f"Saved Time Plot to: {time_plot_path}")

print("=== Data Analysis Completed Successfully! ===")
