[constellation]
group = "BL4S_BEAMLINE_SIM"

[satellites.Tracker_1]
type = "DetectorSatellite"
group = "BL4S_BEAMLINE_SIM"
detector_id = 101

[satellites.Calorimeter_1]
type = "DetectorSatellite"
group = "BL4S_BEAMLINE_SIM"
detector_id = 201

[satellites.Polling_Trigger]
type = "PollingTriggerSatellite"
group = "BL4S_BEAMLINE_SIM"
polling_interval_us = 50

[satellites.Run_Stop_Controller]
type = "StopControllerSatellite"
group = "BL4S_BEAMLINE_SIM"
max_events = 5000

[satellites.Calo_Monitor]
type = "CalorimeterMonitorSatellite"
group = "BL4S_BEAMLINE_SIM"
output_root_file = "calorimeter_out.root"
