import time
import struct
import random
from datetime import datetime, UTC

from constellation.core.configuration import Configuration
from constellation.core.transmitter_satellite import TransmitterSatellite
from constellation.core.message.cdtp2 import DataRecord

class MockScintillator(TransmitterSatellite):
    def do_initializing(self, config: Configuration) -> None:
        self.rate = config.get_float("rate", default_value=100.0)
        self.num_counters = config.get_int("num_counters", default_value=2) # WENDI0, WENDI1
        self._event_number = 0
        self._wendi0_count = 0
        self._wendi1_count = 0
        self.log.info(f"MockScintillator initialized with {self.num_counters} counters at {self.rate} Hz")

    def do_starting(self, run_identifier: str) -> str:
        self._event_number = 0
        self._wendi0_count = 0
        self._wendi1_count = 0
        self.log.info("Starting Scintillator data generation")
        return "Starting"

    def do_run(self) -> str:
        while not self.stop_requested():
            time.sleep(1.0 / self.rate)
            self._event_number += 1
            record = DataRecord(sequence_number=self._event_number, tags={"type": "scaler", "timestamp": str(datetime.now(UTC))})
            
            # Use event_number as seed
            random.seed(self._event_number)
            particle_roll = random.random()
            
            if particle_roll < 0.651:
                particle = 'Pion'
            elif particle_roll < 0.672:
                particle = 'Kaon'
            elif particle_roll < 0.900:
                particle = 'Electron'
            else:
                particle = 'Proton'

            # Neutrons are mostly generated by hadrons hitting W
            if particle in ['Pion', 'Kaon', 'Proton']:
                # Hadrons have high probability of causing a nuclear interaction creating neutrons
                if random.random() < 0.3:
                    self._wendi0_count += 1
                if random.random() < 0.2:
                    self._wendi1_count += 1
            else: # Electron
                # Electromagnetic shower creates very few neutrons
                if random.random() < 0.01:
                    self._wendi0_count += 1
                    self._wendi1_count += 1
            
            # Pack as binary (array of unsigned ints, I = 4 bytes each)
            payload_bytes = struct.pack(f"<2I", self._wendi0_count, self._wendi1_count)
            record.add_block(payload_bytes)
            
            self.send_data_record(record)
        return "Finished run"

def main(args=None):
    from constellation.core.satellite import SatelliteArgumentParser
    from constellation.core.logging import setup_cli_logging
    parser = SatelliteArgumentParser(description="Mock Scintillator (WENDI Scaler) Satellite")
    args = vars(parser.parse_args(args))
    setup_cli_logging(args.pop("level"))
    data_port = args.pop("data_port", 0)
    s = MockScintillator(data_port, **args)
    s.run_satellite()

if __name__ == "__main__":
    main()
