# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bl4s_events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bl4s_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62l4s_events.proto\x12\x04\x62l4s\"L\n\x10\x43\x61lorimeterEvent\x12\n\n\x02\x63h\x18\x01 \x01(\x05\x12\x0e\n\x06\x65nergy\x18\x02 \x01(\x02\x12\x0e\n\x06n_hits\x18\x03 \x01(\x05\x12\x0c\n\x04time\x18\x04 \x01(\x02\";\n\x11ScintillatorEvent\x12\n\n\x02\x63h\x18\x01 \x01(\x05\x12\x0c\n\x04n_pe\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x02\">\n\x0cTimepixEvent\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0b\n\x03tot\x18\x03 \x01(\x02\x12\x0b\n\x03toa\x18\x04 \x01(\x02\"\x1d\n\x0e\x43herenkovEvent\x12\x0b\n\x03qdc\x18\x01 \x01(\x02\"-\n\x0cTriggerEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\"\xff\x01\n\tBL4SEvent\x12\x0b\n\x03sat\x18\x01 \x01(\t\x12-\n\x0b\x63\x61lorimeter\x18\x02 \x01(\x0b\x32\x16.bl4s.CalorimeterEventH\x00\x12/\n\x0cscintillator\x18\x03 \x01(\x0b\x32\x17.bl4s.ScintillatorEventH\x00\x12%\n\x07timepix\x18\x04 \x01(\x0b\x32\x12.bl4s.TimepixEventH\x00\x12)\n\tcherenkov\x18\x05 \x01(\x0b\x32\x14.bl4s.CherenkovEventH\x00\x12%\n\x07trigger\x18\x06 \x01(\x0b\x32\x12.bl4s.TriggerEventH\x00\x42\x0c\n\nevent_datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bl4s_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALORIMETEREVENT']._serialized_start=27
  _globals['_CALORIMETEREVENT']._serialized_end=103
  _globals['_SCINTILLATOREVENT']._serialized_start=105
  _globals['_SCINTILLATOREVENT']._serialized_end=164
  _globals['_TIMEPIXEVENT']._serialized_start=166
  _globals['_TIMEPIXEVENT']._serialized_end=228
  _globals['_CHERENKOVEVENT']._serialized_start=230
  _globals['_CHERENKOVEVENT']._serialized_end=259
  _globals['_TRIGGEREVENT']._serialized_start=261
  _globals['_TRIGGEREVENT']._serialized_end=306
  _globals['_BL4SEVENT']._serialized_start=309
  _globals['_BL4SEVENT']._serialized_end=564
# @@protoc_insertion_point(module_scope)
